export const PRODUCT_TOP_DISCOUNT_REQUEST = "PRODUCT_TOP_DISCOUNT_REQUEST"
export const PRODUCT_TOP_DISCOUNT_SUCCESS = "PRODUCT_TOP_DISCOUNT_SUCCESS"
export const PRODUCT_TOP_DISCOUNT_FAIL = "PRODUCT_TOP_DISCOUNT_FAIL"

export const PRODUCT_TOP_RECOMMEND_REQUEST = "PRODUCT_TOP_RECOMMEND_REQUEST"
export const PRODUCT_TOP_RECOMMEND_SUCCESS = "PRODUCT_TOP_RECOMMEND_SUCCESS"
export const PRODUCT_TOP_RECOMMEND_FAIL = "PRODUCT_TOP_RECOMMEND_FAIL"

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST"
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS"
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL"

export const PRODUCT_TOP_POPULAR_REQUEST = "PRODUCT_TOP_POPULAR_REQUEST"
export const PRODUCT_TOP_POPULAR_SUCCESS = "PRODUCT_TOP_POPULAR_SUCCESS"
export const PRODUCT_TOP_POPULAR_FAIL = "PRODUCT_TOP_POPULAR_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST"
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL"

export const FETCH_AUTHORS_REQUEST = "FETCH_AUTHORS_REQUEST"
export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS"
export const FETCH_AUTHORS_FAIL = "FETCH_AUTHORS_FAIL"
